version: '3.8'

services:
  beps-gpu:
    build:
      context: ../..
      dockerfile: deployment/gpu/Dockerfile
    container_name: beps-gpu
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
      - ../../config:/app/config
    environment:
      - DEVICE=cuda
      - MODEL_NAME=microsoft/DialoGPT-medium
      - MAX_TOKENS=2048
      - TEMPERATURE=0.7
      - CUDA_VISIBLE_DEVICES=0
      - VLLM_WORKER_MULTIPROC_METHOD=spawn
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: beps-redis-gpu
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: